#This playbbok will install HTTP server and start the server.
---
- hosts: appServer
  become: true
  tasks:
    - name: install apache2
      yum: name=httpd state=latest
    - name: Start HTTP Server
      service: name=httpd enabled=yes state=started
    - name: Insert Index Page
      template:
       src: index.html
       dest: /var/www/html/index.html
...
