---
- hosts: tomcatserver
  gather_facts: false
  become: true
  tasks:
  
  - name: uninstall wget
    yum:
     name: wget
     state: present

  - name: uninstall openjdk
    yum:
     name: java-1.8.0-openjdk
     state: present
    
  - name: uninstall jenkins
    yum:
     name: jenkins
     state: present
   
  - 
